// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dag_conf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dag_5fconf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dag_5fconf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "component_conf.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dag_5fconf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dag_5fconf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dag_5fconf_2eproto;
namespace apollo {
namespace cyber {
namespace proto {
class ComponentInfo;
class ComponentInfoDefaultTypeInternal;
extern ComponentInfoDefaultTypeInternal _ComponentInfo_default_instance_;
class DagConfig;
class DagConfigDefaultTypeInternal;
extern DagConfigDefaultTypeInternal _DagConfig_default_instance_;
class ModuleConfig;
class ModuleConfigDefaultTypeInternal;
extern ModuleConfigDefaultTypeInternal _ModuleConfig_default_instance_;
class TimerComponentInfo;
class TimerComponentInfoDefaultTypeInternal;
extern TimerComponentInfoDefaultTypeInternal _TimerComponentInfo_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::cyber::proto::ComponentInfo* Arena::CreateMaybeMessage<::apollo::cyber::proto::ComponentInfo>(Arena*);
template<> ::apollo::cyber::proto::DagConfig* Arena::CreateMaybeMessage<::apollo::cyber::proto::DagConfig>(Arena*);
template<> ::apollo::cyber::proto::ModuleConfig* Arena::CreateMaybeMessage<::apollo::cyber::proto::ModuleConfig>(Arena*);
template<> ::apollo::cyber::proto::TimerComponentInfo* Arena::CreateMaybeMessage<::apollo::cyber::proto::TimerComponentInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace cyber {
namespace proto {

// ===================================================================

class ComponentInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ComponentInfo) */ {
 public:
  ComponentInfo();
  virtual ~ComponentInfo();

  ComponentInfo(const ComponentInfo& from);
  ComponentInfo(ComponentInfo&& from) noexcept
    : ComponentInfo() {
    *this = ::std::move(from);
  }

  inline ComponentInfo& operator=(const ComponentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ComponentInfo& operator=(ComponentInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ComponentInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComponentInfo* internal_default_instance() {
    return reinterpret_cast<const ComponentInfo*>(
               &_ComponentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ComponentInfo* other);
  friend void swap(ComponentInfo& a, ComponentInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComponentInfo* New() const final {
    return CreateMaybeMessage<ComponentInfo>(nullptr);
  }

  ComponentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ComponentInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ComponentInfo& from);
  void MergeFrom(const ComponentInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComponentInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.ComponentInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dag_5fconf_2eproto);
    return ::descriptor_table_dag_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string class_name = 1;
  bool has_class_name() const;
  void clear_class_name();
  static const int kClassNameFieldNumber = 1;
  const std::string& class_name() const;
  void set_class_name(const std::string& value);
  void set_class_name(std::string&& value);
  void set_class_name(const char* value);
  void set_class_name(const char* value, size_t size);
  std::string* mutable_class_name();
  std::string* release_class_name();
  void set_allocated_class_name(std::string* class_name);

  // optional .apollo.cyber.proto.ComponentConfig config = 2;
  bool has_config() const;
  void clear_config();
  static const int kConfigFieldNumber = 2;
  const ::apollo::cyber::proto::ComponentConfig& config() const;
  ::apollo::cyber::proto::ComponentConfig* release_config();
  ::apollo::cyber::proto::ComponentConfig* mutable_config();
  void set_allocated_config(::apollo::cyber::proto::ComponentConfig* config);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ComponentInfo)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_name_;
  ::apollo::cyber::proto::ComponentConfig* config_;
  friend struct ::TableStruct_dag_5fconf_2eproto;
};
// -------------------------------------------------------------------

class TimerComponentInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.TimerComponentInfo) */ {
 public:
  TimerComponentInfo();
  virtual ~TimerComponentInfo();

  TimerComponentInfo(const TimerComponentInfo& from);
  TimerComponentInfo(TimerComponentInfo&& from) noexcept
    : TimerComponentInfo() {
    *this = ::std::move(from);
  }

  inline TimerComponentInfo& operator=(const TimerComponentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimerComponentInfo& operator=(TimerComponentInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TimerComponentInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TimerComponentInfo* internal_default_instance() {
    return reinterpret_cast<const TimerComponentInfo*>(
               &_TimerComponentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TimerComponentInfo* other);
  friend void swap(TimerComponentInfo& a, TimerComponentInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TimerComponentInfo* New() const final {
    return CreateMaybeMessage<TimerComponentInfo>(nullptr);
  }

  TimerComponentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TimerComponentInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TimerComponentInfo& from);
  void MergeFrom(const TimerComponentInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimerComponentInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.TimerComponentInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dag_5fconf_2eproto);
    return ::descriptor_table_dag_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string class_name = 1;
  bool has_class_name() const;
  void clear_class_name();
  static const int kClassNameFieldNumber = 1;
  const std::string& class_name() const;
  void set_class_name(const std::string& value);
  void set_class_name(std::string&& value);
  void set_class_name(const char* value);
  void set_class_name(const char* value, size_t size);
  std::string* mutable_class_name();
  std::string* release_class_name();
  void set_allocated_class_name(std::string* class_name);

  // optional .apollo.cyber.proto.TimerComponentConfig config = 2;
  bool has_config() const;
  void clear_config();
  static const int kConfigFieldNumber = 2;
  const ::apollo::cyber::proto::TimerComponentConfig& config() const;
  ::apollo::cyber::proto::TimerComponentConfig* release_config();
  ::apollo::cyber::proto::TimerComponentConfig* mutable_config();
  void set_allocated_config(::apollo::cyber::proto::TimerComponentConfig* config);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.TimerComponentInfo)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_name_;
  ::apollo::cyber::proto::TimerComponentConfig* config_;
  friend struct ::TableStruct_dag_5fconf_2eproto;
};
// -------------------------------------------------------------------

class ModuleConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ModuleConfig) */ {
 public:
  ModuleConfig();
  virtual ~ModuleConfig();

  ModuleConfig(const ModuleConfig& from);
  ModuleConfig(ModuleConfig&& from) noexcept
    : ModuleConfig() {
    *this = ::std::move(from);
  }

  inline ModuleConfig& operator=(const ModuleConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModuleConfig& operator=(ModuleConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModuleConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModuleConfig* internal_default_instance() {
    return reinterpret_cast<const ModuleConfig*>(
               &_ModuleConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ModuleConfig* other);
  friend void swap(ModuleConfig& a, ModuleConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModuleConfig* New() const final {
    return CreateMaybeMessage<ModuleConfig>(nullptr);
  }

  ModuleConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModuleConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModuleConfig& from);
  void MergeFrom(const ModuleConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModuleConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.ModuleConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dag_5fconf_2eproto);
    return ::descriptor_table_dag_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.cyber.proto.ComponentInfo components = 2;
  int components_size() const;
  void clear_components();
  static const int kComponentsFieldNumber = 2;
  ::apollo::cyber::proto::ComponentInfo* mutable_components(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >*
      mutable_components();
  const ::apollo::cyber::proto::ComponentInfo& components(int index) const;
  ::apollo::cyber::proto::ComponentInfo* add_components();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >&
      components() const;

  // repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
  int timer_components_size() const;
  void clear_timer_components();
  static const int kTimerComponentsFieldNumber = 3;
  ::apollo::cyber::proto::TimerComponentInfo* mutable_timer_components(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >*
      mutable_timer_components();
  const ::apollo::cyber::proto::TimerComponentInfo& timer_components(int index) const;
  ::apollo::cyber::proto::TimerComponentInfo* add_timer_components();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >&
      timer_components() const;

  // optional string module_library = 1;
  bool has_module_library() const;
  void clear_module_library();
  static const int kModuleLibraryFieldNumber = 1;
  const std::string& module_library() const;
  void set_module_library(const std::string& value);
  void set_module_library(std::string&& value);
  void set_module_library(const char* value);
  void set_module_library(const char* value, size_t size);
  std::string* mutable_module_library();
  std::string* release_module_library();
  void set_allocated_module_library(std::string* module_library);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ModuleConfig)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo > components_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo > timer_components_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr module_library_;
  friend struct ::TableStruct_dag_5fconf_2eproto;
};
// -------------------------------------------------------------------

class DagConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.DagConfig) */ {
 public:
  DagConfig();
  virtual ~DagConfig();

  DagConfig(const DagConfig& from);
  DagConfig(DagConfig&& from) noexcept
    : DagConfig() {
    *this = ::std::move(from);
  }

  inline DagConfig& operator=(const DagConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline DagConfig& operator=(DagConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DagConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DagConfig* internal_default_instance() {
    return reinterpret_cast<const DagConfig*>(
               &_DagConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DagConfig* other);
  friend void swap(DagConfig& a, DagConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DagConfig* New() const final {
    return CreateMaybeMessage<DagConfig>(nullptr);
  }

  DagConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DagConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DagConfig& from);
  void MergeFrom(const DagConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DagConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.DagConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_dag_5fconf_2eproto);
    return ::descriptor_table_dag_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
  int module_config_size() const;
  void clear_module_config();
  static const int kModuleConfigFieldNumber = 1;
  ::apollo::cyber::proto::ModuleConfig* mutable_module_config(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >*
      mutable_module_config();
  const ::apollo::cyber::proto::ModuleConfig& module_config(int index) const;
  ::apollo::cyber::proto::ModuleConfig* add_module_config();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >&
      module_config() const;

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.DagConfig)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig > module_config_;
  friend struct ::TableStruct_dag_5fconf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComponentInfo

// optional string class_name = 1;
inline bool ComponentInfo::has_class_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentInfo::clear_class_name() {
  class_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ComponentInfo::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ComponentInfo.class_name)
  return class_name_.GetNoArena();
}
inline void ComponentInfo::set_class_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ComponentInfo.class_name)
}
inline void ComponentInfo::set_class_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ComponentInfo.class_name)
}
inline void ComponentInfo::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ComponentInfo.class_name)
}
inline void ComponentInfo::set_class_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ComponentInfo.class_name)
}
inline std::string* ComponentInfo::mutable_class_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ComponentInfo.class_name)
  return class_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ComponentInfo::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ComponentInfo.class_name)
  if (!has_class_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return class_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentInfo::set_allocated_class_name(std::string* class_name) {
  if (class_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  class_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), class_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ComponentInfo.class_name)
}

// optional .apollo.cyber.proto.ComponentConfig config = 2;
inline bool ComponentInfo::has_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline const ::apollo::cyber::proto::ComponentConfig& ComponentInfo::config() const {
  const ::apollo::cyber::proto::ComponentConfig* p = config_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ComponentInfo.config)
  return p != nullptr ? *p : *reinterpret_cast<const ::apollo::cyber::proto::ComponentConfig*>(
      &::apollo::cyber::proto::_ComponentConfig_default_instance_);
}
inline ::apollo::cyber::proto::ComponentConfig* ComponentInfo::release_config() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ComponentInfo.config)
  _has_bits_[0] &= ~0x00000002u;
  ::apollo::cyber::proto::ComponentConfig* temp = config_;
  config_ = nullptr;
  return temp;
}
inline ::apollo::cyber::proto::ComponentConfig* ComponentInfo::mutable_config() {
  _has_bits_[0] |= 0x00000002u;
  if (config_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::ComponentConfig>(GetArenaNoVirtual());
    config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ComponentInfo.config)
  return config_;
}
inline void ComponentInfo::set_allocated_config(::apollo::cyber::proto::ComponentConfig* config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(config_);
  }
  if (config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  config_ = config;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ComponentInfo.config)
}

// -------------------------------------------------------------------

// TimerComponentInfo

// optional string class_name = 1;
inline bool TimerComponentInfo::has_class_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TimerComponentInfo::clear_class_name() {
  class_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TimerComponentInfo::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TimerComponentInfo.class_name)
  return class_name_.GetNoArena();
}
inline void TimerComponentInfo::set_class_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.TimerComponentInfo.class_name)
}
inline void TimerComponentInfo::set_class_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.TimerComponentInfo.class_name)
}
inline void TimerComponentInfo::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.TimerComponentInfo.class_name)
}
inline void TimerComponentInfo::set_class_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.TimerComponentInfo.class_name)
}
inline std::string* TimerComponentInfo::mutable_class_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TimerComponentInfo.class_name)
  return class_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TimerComponentInfo::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TimerComponentInfo.class_name)
  if (!has_class_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return class_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TimerComponentInfo::set_allocated_class_name(std::string* class_name) {
  if (class_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  class_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), class_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TimerComponentInfo.class_name)
}

// optional .apollo.cyber.proto.TimerComponentConfig config = 2;
inline bool TimerComponentInfo::has_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline const ::apollo::cyber::proto::TimerComponentConfig& TimerComponentInfo::config() const {
  const ::apollo::cyber::proto::TimerComponentConfig* p = config_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TimerComponentInfo.config)
  return p != nullptr ? *p : *reinterpret_cast<const ::apollo::cyber::proto::TimerComponentConfig*>(
      &::apollo::cyber::proto::_TimerComponentConfig_default_instance_);
}
inline ::apollo::cyber::proto::TimerComponentConfig* TimerComponentInfo::release_config() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TimerComponentInfo.config)
  _has_bits_[0] &= ~0x00000002u;
  ::apollo::cyber::proto::TimerComponentConfig* temp = config_;
  config_ = nullptr;
  return temp;
}
inline ::apollo::cyber::proto::TimerComponentConfig* TimerComponentInfo::mutable_config() {
  _has_bits_[0] |= 0x00000002u;
  if (config_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::TimerComponentConfig>(GetArenaNoVirtual());
    config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TimerComponentInfo.config)
  return config_;
}
inline void TimerComponentInfo::set_allocated_config(::apollo::cyber::proto::TimerComponentConfig* config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(config_);
  }
  if (config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  config_ = config;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TimerComponentInfo.config)
}

// -------------------------------------------------------------------

// ModuleConfig

// optional string module_library = 1;
inline bool ModuleConfig::has_module_library() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModuleConfig::clear_module_library() {
  module_library_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ModuleConfig::module_library() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.module_library)
  return module_library_.GetNoArena();
}
inline void ModuleConfig::set_module_library(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  module_library_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ModuleConfig.module_library)
}
inline void ModuleConfig::set_module_library(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  module_library_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ModuleConfig.module_library)
}
inline void ModuleConfig::set_module_library(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  module_library_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ModuleConfig.module_library)
}
inline void ModuleConfig::set_module_library(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  module_library_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ModuleConfig.module_library)
}
inline std::string* ModuleConfig::mutable_module_library() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.module_library)
  return module_library_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ModuleConfig::release_module_library() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ModuleConfig.module_library)
  if (!has_module_library()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return module_library_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ModuleConfig::set_allocated_module_library(std::string* module_library) {
  if (module_library != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  module_library_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), module_library);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ModuleConfig.module_library)
}

// repeated .apollo.cyber.proto.ComponentInfo components = 2;
inline int ModuleConfig::components_size() const {
  return components_.size();
}
inline void ModuleConfig::clear_components() {
  components_.Clear();
}
inline ::apollo::cyber::proto::ComponentInfo* ModuleConfig::mutable_components(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.components)
  return components_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >*
ModuleConfig::mutable_components() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.ModuleConfig.components)
  return &components_;
}
inline const ::apollo::cyber::proto::ComponentInfo& ModuleConfig::components(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.components)
  return components_.Get(index);
}
inline ::apollo::cyber::proto::ComponentInfo* ModuleConfig::add_components() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.ModuleConfig.components)
  return components_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >&
ModuleConfig::components() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.ModuleConfig.components)
  return components_;
}

// repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
inline int ModuleConfig::timer_components_size() const {
  return timer_components_.size();
}
inline void ModuleConfig::clear_timer_components() {
  timer_components_.Clear();
}
inline ::apollo::cyber::proto::TimerComponentInfo* ModuleConfig::mutable_timer_components(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >*
ModuleConfig::mutable_timer_components() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.ModuleConfig.timer_components)
  return &timer_components_;
}
inline const ::apollo::cyber::proto::TimerComponentInfo& ModuleConfig::timer_components(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Get(index);
}
inline ::apollo::cyber::proto::TimerComponentInfo* ModuleConfig::add_timer_components() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >&
ModuleConfig::timer_components() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_;
}

// -------------------------------------------------------------------

// DagConfig

// repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
inline int DagConfig::module_config_size() const {
  return module_config_.size();
}
inline void DagConfig::clear_module_config() {
  module_config_.Clear();
}
inline ::apollo::cyber::proto::ModuleConfig* DagConfig::mutable_module_config(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >*
DagConfig::mutable_module_config() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.DagConfig.module_config)
  return &module_config_;
}
inline const ::apollo::cyber::proto::ModuleConfig& DagConfig::module_config(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Get(index);
}
inline ::apollo::cyber::proto::ModuleConfig* DagConfig::add_module_config() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >&
DagConfig::module_config() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.DagConfig.module_config)
  return module_config_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dag_5fconf_2eproto
