// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/camera/lib/traffic_light/tracker/proto/semantic.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto;
namespace apollo {
namespace perception {
namespace camera {
namespace traffic_light {
namespace tracker {
class SemanticReviseParam;
class SemanticReviseParamDefaultTypeInternal;
extern SemanticReviseParamDefaultTypeInternal _SemanticReviseParam_default_instance_;
}  // namespace tracker
}  // namespace traffic_light
}  // namespace camera
}  // namespace perception
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::perception::camera::traffic_light::tracker::SemanticReviseParam* Arena::CreateMaybeMessage<::apollo::perception::camera::traffic_light::tracker::SemanticReviseParam>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace perception {
namespace camera {
namespace traffic_light {
namespace tracker {

// ===================================================================

class SemanticReviseParam :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam) */ {
 public:
  SemanticReviseParam();
  virtual ~SemanticReviseParam();

  SemanticReviseParam(const SemanticReviseParam& from);
  SemanticReviseParam(SemanticReviseParam&& from) noexcept
    : SemanticReviseParam() {
    *this = ::std::move(from);
  }

  inline SemanticReviseParam& operator=(const SemanticReviseParam& from) {
    CopyFrom(from);
    return *this;
  }
  inline SemanticReviseParam& operator=(SemanticReviseParam&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SemanticReviseParam& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SemanticReviseParam* internal_default_instance() {
    return reinterpret_cast<const SemanticReviseParam*>(
               &_SemanticReviseParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SemanticReviseParam* other);
  friend void swap(SemanticReviseParam& a, SemanticReviseParam& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SemanticReviseParam* New() const final {
    return CreateMaybeMessage<SemanticReviseParam>(nullptr);
  }

  SemanticReviseParam* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SemanticReviseParam>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SemanticReviseParam& from);
  void MergeFrom(const SemanticReviseParam& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SemanticReviseParam* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.perception.camera.traffic_light.tracker.SemanticReviseParam";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto);
    return ::descriptor_table_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 hysteretic_threshold_count = 3 [default = 2];
  bool has_hysteretic_threshold_count() const;
  void clear_hysteretic_threshold_count();
  static const int kHystereticThresholdCountFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 hysteretic_threshold_count() const;
  void set_hysteretic_threshold_count(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional float revise_time_second = 1 [default = 1.5];
  bool has_revise_time_second() const;
  void clear_revise_time_second();
  static const int kReviseTimeSecondFieldNumber = 1;
  float revise_time_second() const;
  void set_revise_time_second(float value);

  // optional float blink_threshold_second = 2 [default = 0.4];
  bool has_blink_threshold_second() const;
  void clear_blink_threshold_second();
  static const int kBlinkThresholdSecondFieldNumber = 2;
  float blink_threshold_second() const;
  void set_blink_threshold_second(float value);

  // @@protoc_insertion_point(class_scope:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 hysteretic_threshold_count_;
  float revise_time_second_;
  float blink_threshold_second_;
  friend struct ::TableStruct_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SemanticReviseParam

// optional float revise_time_second = 1 [default = 1.5];
inline bool SemanticReviseParam::has_revise_time_second() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SemanticReviseParam::clear_revise_time_second() {
  revise_time_second_ = 1.5f;
  _has_bits_[0] &= ~0x00000002u;
}
inline float SemanticReviseParam::revise_time_second() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam.revise_time_second)
  return revise_time_second_;
}
inline void SemanticReviseParam::set_revise_time_second(float value) {
  _has_bits_[0] |= 0x00000002u;
  revise_time_second_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam.revise_time_second)
}

// optional float blink_threshold_second = 2 [default = 0.4];
inline bool SemanticReviseParam::has_blink_threshold_second() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SemanticReviseParam::clear_blink_threshold_second() {
  blink_threshold_second_ = 0.4f;
  _has_bits_[0] &= ~0x00000004u;
}
inline float SemanticReviseParam::blink_threshold_second() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam.blink_threshold_second)
  return blink_threshold_second_;
}
inline void SemanticReviseParam::set_blink_threshold_second(float value) {
  _has_bits_[0] |= 0x00000004u;
  blink_threshold_second_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam.blink_threshold_second)
}

// optional int32 hysteretic_threshold_count = 3 [default = 2];
inline bool SemanticReviseParam::has_hysteretic_threshold_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SemanticReviseParam::clear_hysteretic_threshold_count() {
  hysteretic_threshold_count_ = 2;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SemanticReviseParam::hysteretic_threshold_count() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam.hysteretic_threshold_count)
  return hysteretic_threshold_count_;
}
inline void SemanticReviseParam::set_hysteretic_threshold_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  hysteretic_threshold_count_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.camera.traffic_light.tracker.SemanticReviseParam.hysteretic_threshold_count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace tracker
}  // namespace traffic_light
}  // namespace camera
}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2fcamera_2flib_2ftraffic_5flight_2ftracker_2fproto_2fsemantic_2eproto
